#!/usr/bin/env bash
# -pix_fmt yuv420p for 8bit
# -map 0:a:1 to pick audio track
# subtitles='$f:si=1' to pick subtitle
# do ffmpeg -i "$f" -movflags +faststart -pix_fmt yuv420p -crf 23 -preset veryfast -tune animation -map 0:a:1 -c:v libx264 -c:a aac -filter_complex "subtitles='$f:si=1'" "${f%.*}.mp4"
# -filter_complex "[0:v][0:s]overlay" for bitmap subs
for f in ./$1*.mkv;
do ffmpeg -hide_banner -loglevel error -stats -i "$f" -movflags +faststart -pix_fmt yuv420p -crf 23 -preset veryfast -tune animation -c:v libx264 -c:a aac -filter_complex "subtitles='$f'" "${f%.*}.mp4";
# do ffmpeg -hide_banner -loglevel error -stats -i "$f" -movflags +faststart -pix_fmt yuv420p -crf 23 -preset veryfast -tune animation -c:v libx264 -c:a aac -filter_complex "[0:v][0:s]overlay" "${f%.*}.mp4";
done