#!/usr/bin/env python3
import json
import ntpath
import sys
import subprocess
from urllib.parse import quote
from os import path, listdir

# f = ntpath.basename(sys.argv[1])
domain = "https://u.nisemo.no/"
try:
    prefix = sys.argv[1]
except IndexError:
    prefix = ""

ALLOWED_EXT = (".mp4", ".webm")

for f in listdir(prefix or "."):
    basename, ext = path.splitext(f)
    if ext not in ALLOWED_EXT:
        continue
    fullpath = path.join(prefix, f)
    process = subprocess.Popen(
        [
            "ffprobe",
            "-v",
            "error",
            "-show_entries",
            "format=duration",
            "-of",
            "default=noprint_wrappers=1:nokey=1",
            fullpath,
        ],
        stdout=subprocess.PIPE,
        universal_newlines=True,
    )

    output = process.stdout.readline().strip()
    try:
        output = int(round(float(output), 0))
    except ValueError:
        continue

    subs = path.exists(f"{fullpath[0:-4]}.vtt")

    template = {
        "title": f[0:-4],
        "duration": output,
        "live": False,
        "sources": [
            {
                "url": f"{domain}{prefix}{quote(f)}",
                "contentType": f"video/{ext[1:]}",
                "quality": 1080,
            }
        ],
    }

    if subs:
        template["textTracks"] = [
            {
                "url": f"{domain}{prefix}{quote(f[0:-4])}.vtt",
                "contentType": "text/vtt",
                "name": "English subtitles",
                "default": True,
            }
        ]

    with open(f"{prefix}{f[0:-4]}.json", "w") as outf:
        json.dump(template, outf)

    json_url = f"{domain}{prefix}{quote(f)}".replace(ext, ".json")
    print(json_url)
